{% set name = "slack-sdk" %}
{% set version = "3.36.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slack_sdk-{{ version }}.tar.gz
  sha256: 8586022bdbdf9f8f8d32f394540436c53b1e7c8da9d21e1eab4560ba70cfcffa

build:
  number: 0
  skip: True  # [py<36]

outputs:
  - name: slack-sdk
    script: build_base.bat  # [win]
    script: build_base.sh   # [not win]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
    test:
      source_files:
        - tests
      imports:
        - slack_sdk
        - slack_sdk.web
        - slack_sdk.webhook
        - slack_sdk.signature
        - slack_sdk.socket_mode
        - slack_sdk.audit_logs
        - slack_sdk.scim
        - slack_sdk.oauth
        - slack_sdk.models
        - slack_sdk.rtm
        - slack_sdk.rtm_v2
      requires:
        - pip
        - pytest
        # The old RTM API (slack_sdk.rtm) has a dependency on aiohttp
        - aiohttp >=3.7.3,<4
      commands:
        - pip check
        - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
        - pytest tests

  - name: slack_sdk
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - slack_sdk
      commands:
        - pip check
        - python -c "from importlib.metadata import version; assert(version('{{ name|replace('-', '_') }}')=='{{ version }}')"

about:
  home: https://slack.dev
  summary: The Slack API Platform SDK for Python
  description: |
    The Slack platform offers several APIs to build apps. 
    Each Slack API delivers part of the capabilities from the platform, 
    so that you can pick just those that fit for your needs. 
    This SDK offers a corresponding package for each of Slack's APIs. 
    They are small and powerful when used independently, and work seamlessly 
    when used together, too.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/slackapi/python-slack-sdk
  doc_url: https://slack.dev/python-slack-sdk

extra:
  recipe-maintainers:
    - xylar
    - maresb
