{% set name = "slack-sdk" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slack_sdk-{{ version }}.tar.gz
  sha256: befc1365df93b84eac4592b9a2183411a748ecf662f5c51ce2fa7fdc3f5ee89f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    # listed as extra but testing fails without
    - aiohttp >=3.7.3,<4

test:
  imports:
    - slack
    - slack.rtm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/slackapi/python-slack-sdk
  summary: The Slack API Platform SDK for Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/slackapi/python-slack-sdk
  doc_url: https://github.com/slackapi/python-slack-sdk

extra:
  recipe-maintainers:
    - xylar
