{% set name = "slack-sdk" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slack_sdk-{{ version }}.tar.gz
  sha256: b1748fe130f46d9a8595b9260bc9deb25727a272043b1a8240a935e3c759ac38

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    # listed as extra but testing fails without
    - aiohttp >=3.7.3,<4

test:
  imports:
    - slack
    - slack.rtm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/slackapi/python-slack-sdk
  summary: The Slack API Platform SDK for Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/slackapi/python-slack-sdk
  doc_url: https://github.com/slackapi/python-slack-sdk

extra:
  recipe-maintainers:
    - xylar
