{% set name = "slack-sdk" %}
{% set version = "3.19.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slack_sdk-{{ version }}.tar.gz
  sha256: 47fb4af596243fe6585a92f3034de21eb2104a55cc9fd59a92ef3af17cf9ddd8

build:
  number: 0

outputs:
  - name: slack-sdk
    build:
      skip: True  # [py<36]
      script: python -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
    test:
      imports:
        - slack_sdk
        - slack_sdk.web
        - slack_sdk.webhook
        - slack_sdk.signature
        - slack_sdk.socket_mode
        - slack_sdk.audit_logs
        - slack_sdk.scim
        - slack_sdk.oauth
        - slack_sdk.models
        # The old RTM API has a dependency on aiohttp
        # - slack_sdk.rtm
        - slack_sdk.rtm_v2
      requires:
        - pip
        - aiohttp >=3.7.3,<4
      commands:
        - pip check
        - python -c "import slack_sdk.rtm"

  - name: slack_sdk
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - slack_sdk

about:
  home: https://github.com/slackapi/python-slack-sdk
  summary: The Slack API Platform SDK for Python
  description: |
    The Slack platform offers several APIs to build apps. 
    Each Slack API delivers part of the capabilities from the platform, 
    so that you can pick just those that fit for your needs. 
    This SDK offers a corresponding package for each of Slack's APIs. 
    They are small and powerful when used independently, and work seamlessly 
    when used together, too.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/slackapi/python-slack-sdk
  doc_url: https://slack.dev/python-slack-sdk/

extra:
  recipe-maintainers:
    - xylar
    - maresb
